target 'TRNReactNativeImageCompressor' do
  platform :ios, '9.0'

  rn_path = '../node_modules/react-native'

  pod 'WXImageCompress', '~> 0.1.1'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec"
  pod 'React', path: rn_path, subspecs: [
	'Core',
	'CxxBridge',
	'RCTAnimation',
	'RCTActionSheet',
	'RCTImage',
	'RCTLinkingIOS',
	'RCTNetwork',
	'RCTSettings',
	'RCTText',
	'RCTVibration',
	'RCTWebSocket',
	'RCTPushNotification',
	'RCTCameraRoll',
	'RCTSettings',
	'RCTBlob',
	'RCTGeolocation',
	'DevSupport'
  ]
end
